//
//  EquatableObject.swift
//  Probing
//
//  Created by Kamil Strzelecki on 22/01/2025.
//  Copyright © 2025 Kamil Strzelecki. All rights reserved.
//

/// Defines and implements conformance to the `Equatable` protocol for `final` classes.
///
/// - Important: If any stored property of the class is not `Equatable`, the code generated by the macro will fail to compile.
///
@attached(
    member,
    names: named(==)
)
@attached(
    extension,
    conformances: Equatable
)
public macro EquatableObject() = #externalMacro(
    module: "EquatableObjectMacros",
    type: "EquatableObjectMacro"
)
